<?php

namespace App\Http\Controllers;

use App\Models\Group;
use App\Models\Person;
use App\Services\MunkiExternalUrl;
use Illuminate\Http\Response;
use Illuminate\Support\Str;

class MunkiProfileController extends Controller
{
    public function __construct(private readonly MunkiExternalUrl $externalUrl)
    {
    }

    public function group(Group $group): Response
    {
        return $this->download(
            profileName: "Munki - {$group->name}",
            identifierSuffix: $group->slug,
            clientIdentifier: $group->slug,
            fileName: "munki-{$group->slug}.mobileconfig",
            targetLabel: 'group',
        );
    }

    public function person(Person $person): Response
    {
        $displayName = trim("{$person->first_name} {$person->name}");
        $safeName = Str::of($person->client_identifier)
            ->replaceMatches('/[^A-Za-z0-9._-]+/', '-')
            ->trim('-')
            ->value();

        return $this->download(
            profileName: "Munki - {$displayName}",
            identifierSuffix: $safeName,
            clientIdentifier: $person->client_identifier,
            fileName: "munki-{$safeName}.mobileconfig",
            targetLabel: 'person',
        );
    }

    private function download(
        string $profileName,
        string $identifierSuffix,
        string $clientIdentifier,
        string $fileName,
        string $targetLabel,
    ): Response {
        $mobileconfig = $this->mobileconfig([
            'profileName' => $profileName,
            'identifier' => "com.munkimyadmin.munki.{$identifierSuffix}",
            'payloadUuid' => (string) Str::uuid(),
            'contentUuid' => (string) Str::uuid(),
            'repoUrl' => $this->externalUrl->repoUrl(),
            'clientIdentifier' => $clientIdentifier,
            'targetLabel' => $targetLabel,
        ]);

        return response($mobileconfig, 200, [
            'Content-Disposition' => 'attachment; filename="'.$fileName.'"',
            'Content-Type' => 'application/x-apple-aspen-config',
        ]);
    }

    private function mobileconfig(array $values): string
    {
        $profileName = $this->xml($values['profileName']);
        $identifier = $this->xml($values['identifier']);
        $payloadUuid = $this->xml($values['payloadUuid']);
        $contentUuid = $this->xml($values['contentUuid']);
        $repoUrl = $this->xml($values['repoUrl']);
        $clientIdentifier = $this->xml($values['clientIdentifier']);
        $targetLabel = $this->xml($values['targetLabel']);

        return <<<XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>PayloadContent</key>
    <array>
        <dict>
            <key>ClientIdentifier</key>
            <string>{$clientIdentifier}</string>
            <key>LogToSyslog</key>
            <true/>
            <key>PayloadDescription</key>
            <string>Configure Munki for the {$profileName} {$targetLabel}.</string>
            <key>PayloadDisplayName</key>
            <string>{$profileName}</string>
            <key>PayloadIdentifier</key>
            <string>{$identifier}.managedinstalls</string>
            <key>PayloadType</key>
            <string>ManagedInstalls</string>
            <key>PayloadUUID</key>
            <string>{$contentUuid}</string>
            <key>PayloadVersion</key>
            <integer>1</integer>
            <key>SoftwareRepoURL</key>
            <string>{$repoUrl}</string>
        </dict>
    </array>
    <key>PayloadDescription</key>
    <string>Munki configuration profile generated by Munki My Admin.</string>
    <key>PayloadDisplayName</key>
    <string>{$profileName}</string>
    <key>PayloadIdentifier</key>
    <string>{$identifier}</string>
    <key>PayloadOrganization</key>
    <string>Munki My Admin</string>
    <key>PayloadRemovalDisallowed</key>
    <false/>
    <key>PayloadScope</key>
    <string>System</string>
    <key>PayloadType</key>
    <string>Configuration</string>
    <key>PayloadUUID</key>
    <string>{$payloadUuid}</string>
    <key>PayloadVersion</key>
    <integer>1</integer>
</dict>
</plist>
XML;
    }

    private function xml(string $value): string
    {
        return htmlspecialchars($value, ENT_XML1 | ENT_COMPAT, 'UTF-8');
    }
}
